global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: accounts
    scrape_interval: 5s
    static_configs:
      - targets: ['accounts:9092']

  - job_name: chiefofstate
    scrape_interval: 5s
    static_configs:
      - targets: [ 'chiefofstate:9092' ]
